# Generated by Django 4.0.4 on 2022-05-09 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=120)),
                ('term_min', models.IntegerField(default=10)),
                ('term_max', models.IntegerField(default=30)),
                ('rate_min', models.DecimalField(decimal_places=1, default=1.8, max_digits=4)),
                ('rate_max', models.DecimalField(decimal_places=1, default=9.8, max_digits=4)),
                ('payment_min', models.IntegerField(default=1000000)),
                ('payment_max', models.IntegerField(default=10000000)),
            ],
        ),
    ]
