# Generated by Django 4.0.4 on 2022-05-11 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0002_offer_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='payment',
        ),
    ]
